language: python

servies:
  - docker

python:
  - "2.7"

install:
  - make deps

script:
  - make test

after_success:
  - sudo make docker_build
  - sudo make docker_push

deploy:
  provider: heroku
  app: obscure-brushlands-91700
  api_key: ${HEROKU_API_KEY}
